# Dockerfile

# Imagen base de Node
FROM node:20-alpine

# Carpeta de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json primero
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar todo el código de la app
COPY . .

# Variables de entorno para producción
ENV NODE_ENV=production

# Exponer el puerto (importante para Docker)
EXPOSE 4000

# Comando por defecto
CMD ["npm", "start"]
